# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(blank=True, max_length=50, null=True)),
                ('english', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('prefix', 'prefix'), ('root', 'root'), ('suffix', 'suffix')], default='prefix', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Meaning')),
            ],
        ),
        migrations.AddField(
            model_name='meaning',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Root'),
        ),
    ]
