# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(blank=True, max_length=50, null=True)),
                ('english', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('meaning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prefix.Meaning')),
            ],
        ),
        migrations.AlterField(
            model_name='prefix',
            name='prefix',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prefix.Prefix'),
        ),
    ]
