# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefix', '0002_auto_20161102_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefix.Prefix'),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefix.Meaning'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
